### ISSUE TITLE
New PublicKeyToken in 1.2.1 version

### ISSUE THREAD

**Issue by vkliachkin** [difi/felles-utility-dotnet#18]
No way to resolve conflict between "Difi.Felles.Utility.Resources, Version=1.2.1.0, Culture=neutral, PublicKeyToken=03cc8be9ca792550" and "Difi.Felles.Utility.Resources, Version=1.1.0.0, Culture=neutral, PublicKeyToken=6e6972f540d5419a". Choosing "Difi.Felles.Utility.Resources, Version=1.2.1.0, Culture=neutral, PublicKeyToken=03cc8be9ca792550" arbitrarily.

not possible to use now together difi-sikker-digital-post-klient v 2.0.3 which depends on 1.2.1 and difi-oppslagstjeneste-klient or digipost-signature-api-client using  1.0.0 - 1.2.0 versions

**Comment by aslakjo** [comment]
I do not expect that there will be any issues while upgrading the difi-sikker-digital-post-klient to use version 1.2.1 of Difi.Felles.Utility.Resources. 
Is it possible for you to do the upgrade and send a pull-request? Then we can publish the changes.

**Comment by johnksv** [comment]
Closing. Please open a new issue if the problem still persists.
