### ISSUE TITLE
Support for netstandard

### ISSUE THREAD

**Issue by AndreasLudviksen** [difi/felles-utility-dotnet#22]
We need to use this library from a library.
When do you plan to migrate it to netstandard ?

I see there is an active pull-request - what is the status of that ?

**Comment by johnksv** [comment]
Hi,

Sorry about the late answer. We have now taken a look at this. The next major version (v 4.0.0) is targeted to .netStandard2.0 (#23 ).
Release: https://github.com/difi/felles-utility-dotnet/releases/tag/4.0.0
Nuget: 
- https://www.nuget.org/packages/Difi.Felles.Utility/
- https://www.nuget.org/packages/Difi.Felles.Utility.Resources/


Thank you for raising the issue.

**Comment by AndreasLudviksen** [comment]
Awesome. Thanks.
Does this mean you will release a netstandard-version of sikker-digital-post-klient-dotnet as well ?
